# Generated by Django 2.2.2 on 2019-07-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image1',
            field=models.ImageField(blank=True, upload_to='media/rooms_img/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image2',
            field=models.ImageField(blank=True, upload_to='media/rooms_img/%Y/%m/%d'),
        ),
    ]
