# Generated by Django 2.2.2 on 2019-07-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20190708_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
