# Generated by Django 2.2.2 on 2019-07-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_dataimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimages',
            name='nameOfImage',
            field=models.CharField(default='imageName', max_length=50),
        ),
    ]
