# Generated by Django 2.2.2 on 2019-07-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='constructNameHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=64, unique=True, verbose_name='имя')),
                ('tag_text', models.TextField(blank=True, verbose_name='описание')),
            ],
        ),
    ]
